#________________________________________________________ Find the Difference
# Given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.

#____________________________ Example:
# Input:
# s = "abcd"
# t = "baedc"
# Output: e
# Explanation: 'e' is the letter that was added.

#______ starter
def find_difference(s, t)
  t = t.chars.sort.join
  t.sub!(s, "")
end

puts find_difference("abcd", "baedc") # e

#________________________________________________________ Missing Number
Given an array containing n distinct numbers taken from 0, 1, 2, ..., n, find the one that is missing from the array.

#____________________________ Example 1:
# Input: [3,0,1]
# Output: 2

#____________________________ Example 2:
# Input: [9,6,4,2,3,5,7,0,1]
# Output: 8

#______ starter
def missing_num(arr)
  b = (0..arr.length).to_a
  p b-arr
end

missing_num([3,0,1]) #2


missing_num([9,6,4,2,3,5,7,0,1]) #8